version: "3.8"
services:
  flask-app:
    build:
      context: .
    container_name: flask-app-container1
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-container1
    environment: 
      MYSQL_ROOT_PASSWORD: killswitch20
      MYSQL_DATABASE: finco_ops_data_db
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
